repos:

  - repo: local
    hooks:
      - id: pytest
        name: pytest (unit tests)
        entry: pytest tests/unit --maxfail=1 --disable-warnings -q
        language: system
        pass_filenames: false