site_name: Trading Framework
site_url: https://RBrouq.github.io/trading-framework  # optionnel, pour GitHub Pages
docs_dir: docs
nav:
  - Home: index.md
  - API Reference:
      - Overview: api_overview.md
      - Logging: logging_config.md
      - Main: main_module.md

theme:
  name: material      # si tu as installé mkdocs-material
  palette:
    primary: 'indigo'
    accent: 'indigo'