site_name: Trading Framework
site_url: https://RBrouq.github.io/trading-framework
docs_dir: docs
nav:
  - Home: index.md
  - API Reference:
      - Overview: api_overview.md
      - Logging: logging_config.md
      - Main: main_module.md
  - Guide:
    - Installation: guide/install.md
    - Quickstart: guide/quickstart.md
  - Changelog: changelog.md
  - API: api/
  
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'