name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-lock.txt') }}

      - name: Install dependencies (prod + dev)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Check formatting with Black
        run: black . --check --line-length=79

      - name: Lint & auto-fix with Ruff
        run: ruff check . --exit-zero

      - name: Type check with mypy
        run: mypy src/trading_framework

      - name: Run tests with coverage
        run: pytest --cov=src --cov-report=xml

      - name: Upload coverage to Codecov
        if: github.event_name != 'pull_request'
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml